logs:
    dir_logs: logs/vqa2/mutan_noatt_train
vqa:
    dataset: VQA2
    dir: data/vqa2
    trainsplit: train
    nans: 2000
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
    path_trainset: 'data/vqa2/processed/nans,2000_maxlength,26_minwcount,0_nlp,mcb_pad,right_trainsplit,train/'
    path_comp_pairs: 'data/vqa2/raw/annotations/v2_mscoco_train2014_complementary_pairs.json'
coco:
    dir: data/coco
    arch: fbresnet152
    mode: noatt
    size: 448
    path_raw: 'data/coco/extract/arch,fbresnet152_size,448/'
    path_knn: 'data/coco/knn/mscoco_train2014_nn_images.json'
model:
    arch: MutanNoAtt
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    fusion:
        dim_v: 2048
        dim_q: 2400
        dim_hv: 360
        dim_hq: 360
        dim_mm: 360
        R: 10
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: tanh
        activation_q: tanh
        dropout_hv: 0
        dropout_hq: 0
    classif:
        dropout: 0.5
cx_model:
    name: 'neuralcx_300_2_all'
    pretrained_vqa: true
    trainable_vqa: false
    dim_h: 300
    n_layers: 2
    drop_p: 0.25
    v_emb: true
    v_mult: true
    v_dist: true
    v_rank: true
    q_emb: true
    pretrained_emb: true
    a_emb: true
    z_emb: true
optim:
    lr: 0.0001
    batch_size: 64
    epochs: 100
